<a href="https://colab.research.google.com/github/Filip3ra/CNTP3_aiNet/blob/master/TP3_CN_aiNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TP3 Computação Natural - Algoritmo aiNet**

In [1]:
import math
import numpy as np
import random

Dados de entrada e constantes:

In [2]:
ITEMS_DATA = np.array([[1.60, 0.70],
                       [1.53, 0.60],
                       [1.62, 0.68],
                       [1.64, 0.90],
                       
                       [1.85, 0.03],
                       [1.84, 0.09],
                       [1.89, 0.10],
                       [1.90, 0.12],
                       [1.83, 0.06]])

ITEMS_QUANTITY = GRID_SIZE = ITEMS_DATA.shape[0]

Gera a Grade:

In [3]:
def generate_new_grid():
  return np.full((GRID_SIZE, GRID_SIZE), 0)

grid = generate_new_grid()

print(grid)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


Gera Anticorpos: A população Ab de anticorpos é composta por duas subpopulações, a **Abm** (anticorpos de memória) e a **Abr** (anticorpos restantes).

In [4]:
def generate_antibodies():
  quantity = 10
  antibodies = []

  for _ in range(math.floor(quantity / 2)):
    random_height = random.uniform(1.8, 2.0)
    random_score = random.uniform(0, 0.1)
    antibodies.append([random_height, random_score])

  for _ in range(math.floor(quantity / 2)):
    random_height = random.uniform(1.5, 1.65)
    random_score = random.uniform(0.8, 1)
    antibodies.append([random_height, random_score])

  return np.array(antibodies)

Calcula Afinidade com Antígeno:

1) Seleciona um antígeno da população (Ag).

2) Para cada elemento da população de Ab calculamos a afinidade ao antigeno selecionado. (Inverso da distância euclidiana)

3) Seleciona os **n** anticorpos de afinidade mais alta

In [14]:
ANTIBODIES = generate_antibodies()

size_1 = int((ANTIBODIES.size)/2)
size_2 = int((ITEMS_DATA.size/2))


sum_affinity = 0.0
sum_array = []

for i in range(size_1):
  anti_body = ANTIBODIES[i]
  print("atibodie = ", anti_body)

  for j in range(size_2):
    pow_1 = math.pow(ITEMS_DATA[j][0] - anti_body[0], 2)
    pow_2 = math.pow(ITEMS_DATA[j][1] - anti_body[1], 2)    
    affinity = 1/(math.sqrt(pow_1 + pow_2))
    sum_affinity += affinity

    #print("um = ", ITEMS_DATA[j][0], "dois = ", ITEMS_DATA[j][1])
    print(affinity)
  print("Afinidade total = ", sum_affinity)
  sum_array.append(sum_affinity)
  sum_affinity = 0.0

for k in range(len(sum_array)):
  print(sum_array[k])

atibodie =  [1.87819931 0.0155926 ]
1.353567489208305
1.4699926549432154
1.4028901329871082
1.0917945623207777
31.579006082964128
11.956003058309372
11.733189835974647
9.375660145947233
15.258392889158136
Afinidade total =  85.22049685181291
atibodie =  [1.98187891 0.07407206]
1.3638398942041845
1.4421822490334246
1.4169011287927247
1.1187067137439526
7.191752414140866
7.0042639034548095
10.47479880810628
10.651849874387043
6.556112032767669
Afinidade total =  47.22040701863095
atibodie =  [1.98625245 0.04312764]
1.3123040263395136
1.389058877647846
1.3611461994287968
1.0820324819572358
7.305487844969027
6.511267117398877
8.944629792184728
8.655220754420164
6.362911457736384
Afinidade total =  42.92405855208257
atibodie =  [1.83430081 0.02371987]
1.3971991225242744
1.5344756836047126
1.4484717264928741
1.1141276955487296
59.14110680052264
15.032010073585397
10.587461095760135
8.579268394328329
27.371645847278263
Afinidade total =  126.20576643964534
atibodie =  [1.85304993 0.01005283]
